services:
  qwen2api:
    container_name: qwen2api
    image: rfym21/qwen2api:latest
    restart: always
    ports:
      - "2116:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./caches:/app/caches
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - qwen2api
      - apinetwork

  redis:
    image: redis:7.2-alpine
    container_name: qwen2api_redis
    restart: always
    volumes:
      - qwen2api_redis:/data
    networks:
      - qwen2api

volumes:
  qwen2api_redis:

networks:
  qwen2api:
    name: qwen2api
  apinetwork:
    name: apinetwork
